info:
  name: 多个数据生成测试
  description: 配置多个顺序数据，用于生成攻击链
http: 
  data:
    - description: "通过POST请求示例"
      ip_pair:
        src_ip: 93.68.89.21
        src_port: RANDOM
        dst_ip: 172.168.1.200
        dst_port: 80  
      request:
        format: plain
        req_data: |
          POST /page/index.php HTTP/1.1
          Host: example.com
          Content-Length: 11
          Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
          Accept-Language: en
          Content-Type: application/x-www-form-urlencoded
          User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)

          id=7788
      response:
        format: plain
        resp_data: |
          HTTP/1.1 200 OK
          Content-Type: application/json
          Content-Length: 126

          {"msg":"success","retString":"0"}
udp:
  data:
    - description: "UDP通信测试 - 模拟UDP协议的请求响应通信"
      ip_pair:
        src_ip: 93.68.89.21
        src_port: RANDOM
        dst_ip: 172.17.1.200
        dst_port: 9966
      request:
        format: plain
        req_data: "UDP Request Data"
      response:
        format: plain
        resp_data: "UDP Response Data"
http:
  data:
    - description: "GET请求用例"
      ip_pair:
        src_ip: 72.38.89.21
        src_port: RANDOM
        dst_ip: 172.168.1.200
        dst_port: 80  
      request:
        format: plain
        req_data: |
          GET /details?id=1 HTTP/1.1
          Host: 121.161.72.131
          Content-Length: 0
      response:
        format: plain
        resp_data: |
          HTTP/1.1 200 OK
          Server: nginx/1.22.0
          Date: Tue, 22 Apr 2025 03:22:20 GMT
          Content-Type: text/html
          Content-Length: 111
          Connection: close

          <html>
          <head><title></title></head>
          <body>
            repsonse ok
          </body>
          </html>