info:
  name: 表达式执行
  description: 测试用例
http:
  data:
    - description: "表达式注入"
      ip_pair:
        src_ip: 93.68.9.21
        src_port: 7788
        dst_ip: 172.168.100.200
        dst_port: 80  
      request:
        format: plain
        req_data: |
          GET /?id=1ewterH%25{8*8} HTTP/1.1
          Accept: */*
          Accept-Language: en
          Connection: close
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.4.15
      response:
        format: plain
        resp_data: |
          HTTP/1.1 404 Not Found
          Server: nginx/1.22.0
          Date: Tue, 22 Apr 2025 06:07:50 GMT
          Content-Type: text/html
          Connection: close

          <html>
            <head><title>404 Not Found</title></head>
            <body>
            <center><h1>404 Not Found</h1></center>
            <hr><center>nginx/1.22.0</center>
          </body>
          </html>